ECommerceSite/EcommerceSite/Controllers/AddToCartsController.cs
using EcommerceSite.Models;
using EcommerceSite.Models.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace EcommerceSite.Controllers
{
    public class AddToCartsController : Controller
    {
        bool status = false;
        ECommerceDbContext db = new ECommerceDbContext();

        public static List<CartProduct> cartProducts = new List<CartProduct>();
        public JsonResult AddToCart(int id,int qty)
        {
            var ProductById = db.Products.Where(m => m.Id == id).FirstOrDefault();

            CartProduct cartProduct = new CartProduct();
            cartProduct.Id = 0;
            cartProduct.Name = ProductById.Name;
            cartProduct.Qty = qty;
            cartProduct.Image = ProductById.Image;
            cartProduct.Price = ProductById.Price;
            cartProduct.UserInfo = null;
            cartProduct.UserInfoId = 0;

            cartProducts.Add(cartProduct);

            if (cartProducts != null && cartProducts.Count > 0)
            {
                status = true;
            }
            if (status == true)
            {
                return Json(1);
            }
            return Json(0);
        }
        public JsonResult AddToCartManProduct(int id, int qty)
        {
            var ProductById = db.MansProducts.Where(m => m.Id == id).FirstOrDefault();

            CartProduct cartProduct = new CartProduct();
            cartProduct.Id = 0;
            cartProduct.Name = ProductById.Name;
            cartProduct.Qty = qty;
            cartProduct.Image = ProductById.Image;
            cartProduct.Price = ProductById.Price;
            cartProduct.UserInfo = null;
            cartProduct.UserInfoId = 0;

            cartProducts.Add(cartProduct);

            if (cartProducts != null && cartProducts.Count > 0)
            {
                status = true;
            }
            if (status == true)
            {
                return Json(1);
            }
            return Json(0);
        }
        public JsonResult AddToCartWomanProduct(int id, int qty)
        {
            var ProductById = db.WomansProducts.Where(m => m.Id == id).FirstOrDefault();

            CartProduct cartProduct = new CartProduct();
            cartProduct.Id = 0;
            cartProduct.Name = ProductById.Name;
            cartProduct.Qty = qty;
            cartProduct.Image = ProductById.Image;
            cartProduct.Price = ProductById.Price;
            cartProduct.UserInfo = null;
            cartProduct.UserInfoId = 0;

            cartProducts.Add(cartProduct);

            if (cartProducts != null && cartProducts.Count > 0)
            {
                status = true;
            }
            if (status == true)
            {
                return Json(1);
            }
            return Json(0);
        }
        public JsonResult AddToCartTourPackege(int id, int qty)
        {
            var ProductById = db.TourPackeges.Where(m => m.Id == id).FirstOrDefault();

            CartProduct cartProduct = new CartProduct();
            cartProduct.Id = 0;
            cartProduct.Name = ProductById.Name;
            cartProduct.Qty = qty;
            cartProduct.Image = ProductById.Image;
            cartProduct.Price = ProductById.Cost;
            cartProduct.UserInfo = null;
            cartProduct.UserInfoId = 0;

            cartProducts.Add(cartProduct);

            if (cartProducts != null && cartProducts.Count > 0)
            {
                status = true;
            }
            if (status == true)
            {
                return Json(1);
            }
            return Json(0);
        }


        public static List<Product> products = new List<Product>();
        public static List<Product> foodProducts = new List<Product>();
        public static List<Product> moreProducts = new List<Product>();
        public static List<MansProduct> manProducts = new List<MansProduct>();
        public static List<WomansProduct> womanProducts = new List<WomansProduct>();
        public static List<TourPackege> tourPackeges = new List<TourPackege>();

        public JsonResult AddToCompare(int id)
        {
            var ProductById = db.Products.Where(m => m.Id == id).FirstOrDefault();

            if (ProductById.Brand.Category.MasterCategory.Id == 8)
            {
                if (products.Count < 3)
                {
                    products.Add(ProductById);
                    if (products != null && products.Count > 0)
                    {
                        status = true;
                    }
                    if (status == true)
                    {
                        return Json(1);
                    }
                }
            }

            if (ProductById.Brand.Category.MasterCategory.Id == 9)
            {
                if (foodProducts.Count < 3)
                {
                    foodProducts.Add(ProductById);
                    if (foodProducts != null && foodProducts.Count > 0)
                    {
                        status = true;
                    }
                    if (status == true)
                    {
                        return Json(1);
                    }
                }
            }
            if (ProductById.Brand.Category.MasterCategory.Id == 13)
            {
                if (moreProducts.Count < 3)
                {
                    moreProducts.Add(ProductById);
                    if (moreProducts != null && moreProducts.Count > 0)
                    {
                        status = true;
                    }
                    if (status == true)
                    {
                        return Json(1);
                    }
                }
            }
            return Json(0);
        }
        public JsonResult AddToCompareManProduct(int id)
        {
            var ProductById = db.MansProducts.Where(m => m.Id == id).FirstOrDefault();

            if (manProducts.Count < 3)
            {
                manProducts.Add(ProductById);

                if (manProducts != null && manProducts.Count > 0)
                {
                    status = true;
                }
                if (status == true)
                {
                    return Json(1);
                }
            }
            return Json(0);
        }
        public JsonResult AddToCompareWomanProduct(int id)
        {
            var ProductById = db.WomansProducts.Where(m => m.Id == id).FirstOrDefault();

            if (womanProducts.Count < 3)
            {
                womanProducts.Add(ProductById);

                if (womanProducts != null && womanProducts.Count > 0)
                {
                    status = true;
                }
                if (status == true)
                {
                    return Json(1);
                }
            }
            return Json(0);
        }
        public JsonResult AddToCompareTourPackege(int id)
        {
            var ProductById = db.TourPackeges.Where(m => m.Id == id).FirstOrDefault();

            if (tourPackeges.Count < 3)
            {
                tourPackeges.Add(ProductById);

                if (tourPackeges != null && tourPackeges.Count > 0)
                {
                    status = true;
                }
                if (status == true)
                {
                    return Json(1);
                }
            }
            return Json(0);
        }

        

        //--------------------------------------------
        public ActionResult ResetCompareProductList()
        {
            products = new List<Product>();
            return View("~/Views/AddToCarts/CompareProducts.cshtml", products);
        }
        public ActionResult ResetCompareFoodProductList()
        {
            foodProducts = new List<Product>();
            return View("~/Views/AddToCarts/CompareFoodProducts.cshtml", foodProducts);
        }
        public ActionResult ResetCompareManProductList()
        {
            manProducts = new List<MansProduct>();
            return View("~/Views/AddToCarts/CompareManProducts.cshtml", manProducts);

        }
        public ActionResult ResetCompareWomanProductList()
        {
            womanProducts = new List<WomansProduct>();
            return View("~/Views/AddToCarts/CompareWomanProducts.cshtml", womanProducts);
        }
        public ActionResult ResetCompareTourPackegeList()
        {
            tourPackeges = new List<TourPackege>();
            return View("~/Views/AddToCarts/CompareTourPackeges.cshtml", tourPackeges);
        }
        public ActionResult ResetCompareMoreProductList()
        {
            moreProducts = new List<Product>();
            return View("~/Views/AddToCarts/CompareMoreProducts.cshtml", moreProducts);
        }



        //---------------------------------------------
        public ActionResult CompareProducts()
        {
            var productList = products.ToList();    
            return View(productList);
        }
        public ActionResult CompareFoodProducts()
        {
            var productList = foodProducts.ToList();
            return View(productList);
        }
        public ActionResult CompareManProducts()
        {
            var productList = manProducts.ToList();
            return View(productList);
        }
        public ActionResult CompareWomanProducts()
        {
            var productList = womanProducts.ToList();
            return View(productList);
        }
        public ActionResult CompareTourPackeges()
        {
            var productList = tourPackeges.ToList();
            return View(productList);
        }
        public ActionResult CompareMoreProducts()
        {
            var productList = moreProducts.ToList();
            return View(productList);
        }

        public ActionResult ShowCartListAndBuy()
        {
            UserInfo userInfo = new UserInfo();

ECommerceSite/EcommerceSite/Views/AddToCarts/CartDetails.cshtml
@model EcommerceSite.Models.UserInfo

@{
    ViewBag.Title = "CartDetails";
    Layout = "~/Views/Shared/_LayoutPageForUser.cshtml";
}

<h2>Buy Details</h2>

<div class="row">
    <div class="col-md-12">

        <h4>Buy Result</h4>
        <hr />
        <table>
            <tr>
                <td> Email Or Phone :</td>
                <td>&nbsp;@Html.DisplayFor(model => model.EmailOrPhone)</td>
            </tr>
            <tr>
                <td>Name :</td>
                <td>&nbsp; @Html.DisplayFor(model => model.Name)</td>
            </tr>
            <tr>
                <td>Gander :</td>
                <td>&nbsp; @Html.DisplayFor(model => model.Gander)</td>
            </tr>
            <tr>
                <td>Profession :</td>
                <td>&nbsp;@Html.DisplayFor(model => model.Profession)</td>
            </tr>
            <tr>
                <td>Birth Day :</td>
                <td>&nbsp;@Html.DisplayFor(model => model.DateOfBirth)</td>
            </tr>
            <tr>
                <td>Address :</td>
                <td>&nbsp;@Html.DisplayFor(model => model.Address)</td>
            </tr>
        </table>
        <br />
        <br />
        <br />
        <h4>Item Details</h4>
        <table class="table table-bordered table-condensed table-striped table-responsive">
            <thead>
                <tr>
                    <th>
                        Image
                    </th>
                    <th>
                        Product Name
                    </th>
                    <th>
                        Quantity
                    </th>
                    <th>
                        Price
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model.CartProducts != null && Model.CartProducts.Count > 0)
                {
                    foreach (var item in Model.CartProducts)
                    {
                        <tr>
                            <td>
                                @if (item.Image != null)
                                {
                                    string base64Image = Convert.ToBase64String(item.Image);
                                    string Image = string.Format("data:image/gif;base64,{0}", base64Image);
                                    <img src="@Image" width="100" height="100" />
                                }
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Qty)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Price)
                            </td>

                        </tr>
                    }
                    <tr>
                        <td></td>
                        <td><b>Total :</b></td>
                        @{
                            decimal sum = 0;
                            foreach (var item in Model.CartProducts)
                            {

                                sum = sum + item.Price * (decimal)item.Qty;
                            }
                            <td>
                                <b>
                                    @(sum)
                                </b>
                            </td>
                        }
                    </tr>
                }
                else
                {
                    <tr>
                        <td colspan="3">Your cart is empty</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

ECommerceSite/EcommerceSite/Views/AddToCarts/CompareFoodProducts.cshtml
@model IEnumerable<EcommerceSite.Models.Product>

@{
    ViewBag.Title = "CompareFoodProducts";
    Layout = "~/Views/Shared/_LayoutPageForUser.cshtml";
}

<h2>Compare Food Products</h2>
<p>
    @Html.ActionLink("Reset List", "ResetCompareFoodProductList", "AddToCarts", null, new { @class = "btn btn-sm btn-primary" })
</p>
@if (Model != null && Model.Count() > 0)
{
<table class="table table-bordered table-condensed table-striped table-responsive List-table ">
    <tr>
        <td>
            <b>@Html.DisplayNameFor(model => model.Image)</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @if (item.Image != null)
                {
                    string base64Image = Convert.ToBase64String(item.Image);
                    string Image = string.Format("data:image/gif;base64,{0}", base64Image);
                    <img src="@Image" width="250" height="300" />
                }

            </td>
        }

    </tr>
    <tr>
        <td>
            <b>Product Name</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>

        }

    </tr>
    <tr>
        <td>
            <b>Brand Name</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Brand.Name)
            </td>
        }
    </tr>
    <tr>
        <td>
            <b>Type Name</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Type.Name)
            </td>
        }
    </tr>
    <tr>
        <td>
            <b>@Html.DisplayNameFor(model => model.Feature)</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Feature)
            </td>

        }
    </tr>
    <tr>
        <td>
            <b> @Html.DisplayNameFor(model => model.Description)</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
        }
    </tr>
    <tr>
        <td>
            <b>@Html.DisplayNameFor(model => model.Price)</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
        }
    </tr>
</table>
}
else
{
    <h3 style="color:red">List is empty. You need to add first</h3>
}

ECommerceSite/EcommerceSite/Views/AddToCarts/CompareManProducts.cshtml
@model IEnumerable<EcommerceSite.Models.MansProduct>

@{
    ViewBag.Title = "CompareManProducts";
    Layout = "~/Views/Shared/_LayoutPageForUser.cshtml";
}

<h2>Compare Mans Products</h2>
<p>
    @Html.ActionLink("Reset List", "ResetCompareManProductList", "AddToCarts", null, new { @class = "btn btn-sm btn-primary" })
</p>
@if (Model != null && Model.Count() > 0)
{
<table class="table table-bordered table-condensed table-striped table-responsive List-table ">
    <tr>
        <td>
            <b>@Html.DisplayNameFor(model => model.Image)</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @if (item.Image != null)
                {
                    string base64Image = Convert.ToBase64String(item.Image);
                    string Image = string.Format("data:image/gif;base64,{0}", base64Image);
                    <img src="@Image" width="250" height="300" />
                }

            </td>
        }

    </tr>
    <tr>
        <td>
            <b>Product Name</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>

        }

    </tr>
    <tr>
        <td>
            <b>Brand Name</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Brand.Name)
            </td>
        }
    </tr>
    <tr>
        <td>
            <b>Size</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Size.SizeTitle)
            </td>
        }
    </tr>
    <tr>
        <td>
            <b>Colour</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Colour.ColourName)
            </td>

        }
    </tr>
    <tr>
        <td>
            <b> @Html.DisplayNameFor(model => model.Description)</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
        }
    </tr>
    <tr>
        <td>
            <b>@Html.DisplayNameFor(model => model.Price)</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
        }
    </tr>
</table>
}
else
{
    <h3 style="color:red">List is empty. You need to add first</h3>
}

ECommerceSite/EcommerceSite/Views/AddToCarts/CompareMoreProducts.cshtml
@model IEnumerable<EcommerceSite.Models.Product>

@{
    ViewBag.Title = "CompareMoreProducts";
    Layout = "~/Views/Shared/_LayoutPageForUser.cshtml";
}

<h2>Compare More Products</h2>
<p>
    @Html.ActionLink("Reset List", "ResetCompareMoreProductList", "AddToCarts", null, new { @class = "btn btn-sm btn-primary" })
</p>
@if (Model != null && Model.Count() > 0)
{
    <table class="table table-bordered table-condensed table-striped table-responsive List-table ">
        <tr>
            <td>
                <b>@Html.DisplayNameFor(model => model.Image)</b>
            </td>
            @foreach (var item in Model)
            {
                <td>
                    @if (item.Image != null)
                    {
                        string base64Image = Convert.ToBase64String(item.Image);
                        string Image = string.Format("data:image/gif;base64,{0}", base64Image);
                        <img src="@Image" width="250" height="300" />
                    }

                </td>
            }

        </tr>
        <tr>
            <td>
                <b>Product Name</b>
            </td>
            @foreach (var item in Model)
            {
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

            }

        </tr>
        <tr>
            <td>
                <b>Brand Name</b>
            </td>
            @foreach (var item in Model)
            {
                <td>
                    @Html.DisplayFor(modelItem => item.Brand.Name)
                </td>
            }
        </tr>
        <tr>
            <td>
                <b>Type Name</b>
            </td>
            @foreach (var item in Model)
            {
                <td>
                    @Html.DisplayFor(modelItem => item.Type.Name)
                </td>
            }
        </tr>
        <tr>
            <td>
                <b>@Html.DisplayNameFor(model => model.Feature)</b>
            </td>
            @foreach (var item in Model)
            {
                <td>
                    @Html.DisplayFor(modelItem => item.Feature)
                </td>

            }
        </tr>
        <tr>
            <td>
                <b> @Html.DisplayNameFor(model => model.Description)</b>
            </td>
            @foreach (var item in Model)
            {
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
            }
        </tr>
        <tr>
            <td>
                <b>@Html.DisplayNameFor(model => model.Price)</b>
            </td>
            @foreach (var item in Model)
            {
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
            }
        </tr>
    </table>
}
else
{
    <h3 style="color:red">List is empty. You need to add first</h3>
}

ECommerceSite/EcommerceSite/Views/AddToCarts/CompareProducts.cshtml
@model IEnumerable<EcommerceSite.Models.Product>

@{
    ViewBag.Title = "CompareProducts";
    Layout = "~/Views/Shared/_LayoutPageForUser.cshtml";
}

<h2>Compare Products</h2>
<p>
    @Html.ActionLink("Reset List", "ResetCompareProductList", "AddToCarts", null, new { @class = "btn btn-sm btn-primary" })
</p>
@if (Model != null && Model.Count() > 0)
{
<table class="table table-bordered table-condensed table-striped table-responsive List-table ">
    <tr>
        <td>
            <b>@Html.DisplayNameFor(model => model.Image)</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @if (item.Image != null)
                {
                    string base64Image = Convert.ToBase64String(item.Image);
                    string Image = string.Format("data:image/gif;base64,{0}", base64Image);
                    <img src="@Image" width="250" height="300" />
                }

            </td>
        }

    </tr>
    <tr>
        <td>
            <b>Product Name</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>

        }

    </tr>
    <tr>
        <td>
            <b>Brand Name</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Brand.Name)
            </td>
        }
    </tr>
    <tr>
        <td>
            <b>Type Name</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Type.Name)
            </td>
        }
    </tr>
    <tr>
        <td>
            <b>@Html.DisplayNameFor(model => model.Feature)</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Feature)
            </td>

        }
    </tr>
    <tr>
        <td>
            <b> @Html.DisplayNameFor(model => model.Description)</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
        }
    </tr>
    <tr>
        <td>
            <b>@Html.DisplayNameFor(model => model.Price)</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
        }
    </tr>
</table>
}
else
{
    <h3 style="color:red">List is empty. You need to add first</h3>
}

ECommerceSite/EcommerceSite/Views/AddToCarts/CompareTourPackeges.cshtml
@model IEnumerable<EcommerceSite.Models.TourPackege>

@{
    ViewBag.Title = "CompareTourPackeges";
    Layout = "~/Views/Shared/_LayoutPageForUser.cshtml";
}

<h2>Compare Tour Packeges</h2>
<p>
    @Html.ActionLink("Reset List", "ResetCompareTourPackegeList", "AddToCarts", null, new { @class = "btn btn-sm btn-primary" })
</p>
@if (Model != null && Model.Count() > 0)
{
<table class="table table-bordered table-condensed table-striped table-responsive List-table ">
    <tr>
        <td>
            <b>@Html.DisplayNameFor(model => model.Image)</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @if (item.Image != null)
                {
                    string base64Image = Convert.ToBase64String(item.Image);
                    string Image = string.Format("data:image/gif;base64,{0}", base64Image);
                    <img src="@Image" width="250" height="300" />
                }

            </td>
        }

    </tr>
    <tr>
        <td>
            <b>Product Name</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>

        }

    </tr>
    <tr>
        <td>
            <b>Category</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
        }
    </tr>
    <tr>
        <td>
            <b>Destination Name</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.DestinationPlace.Name)
            </td>
        }
    </tr>
    <tr>
        <td>
            <b>@Html.DisplayNameFor(model => model.Cost)</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Cost)
            </td>
        }
    </tr>
</table>
}
else
{
    <h3 style="color:red">List is empty. You need to add first</h3>
}

ECommerceSite/EcommerceSite/Views/AddToCarts/CompareWomanProducts.cshtml
@model IEnumerable<EcommerceSite.Models.WomansProduct>

@{
    ViewBag.Title = "CompareWomanProducts";
    Layout = "~/Views/Shared/_LayoutPageForUser.cshtml";
}

<h2>Compare Womans Products</h2>
<p>
    @Html.ActionLink("Reset List", "ResetCompareWomanProductList", "AddToCarts", null, new { @class = "btn btn-sm btn-primary" })
</p>
@if (Model != null && Model.Count() > 0)
{
<table class="table table-bordered table-condensed table-striped table-responsive List-table ">
    <tr>
        <td>
            <b>@Html.DisplayNameFor(model => model.Image)</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @if (item.Image != null)
                {
                    string base64Image = Convert.ToBase64String(item.Image);
                    string Image = string.Format("data:image/gif;base64,{0}", base64Image);
                    <img src="@Image" width="250" height="300" />
                }

            </td>
        }

    </tr>
    <tr>
        <td>
            <b>Product Name</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>

        }

    </tr>
    <tr>
        <td>
            <b>Brand Name</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Brand.Name)
            </td>
        }
    </tr>
    <tr>
        <td>
            <b>Size</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Size.SizeTitle)
            </td>
        }
    </tr>
    <tr>
        <td>
            <b>Colour</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Colour.ColourName)
            </td>

        }
    </tr>
    <tr>
        <td>
            <b> @Html.DisplayNameFor(model => model.Description)</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
        }
    </tr>
    <tr>
        <td>
            <b>@Html.DisplayNameFor(model => model.Price)</b>
        </td>
        @foreach (var item in Model)
        {
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
        }
    </tr>
</table>
}
else
{
    <h3 style="color:red">List is empty. You need to add first</h3>
}